/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package palindrome;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author abans tangalle
 */
public class palindromefram extends javax.swing.JFrame {

    /**
     * Creates new form palindromefram
     */
    public palindromefram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtString = new javax.swing.JTextField();
        txtResults = new javax.swing.JTextField();
        txtReverse = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Palindrome");

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Minion Pro Med", 2, 36)); // NOI18N
        jLabel2.setText("Check String is a Palindrome or Not");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 70, 520, 50);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("Enter String :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 140, 160, 50);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Reverse         :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 240, 150, 40);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Result             :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 330, 150, 40);

        txtString.setBackground(new java.awt.Color(255, 255, 204));
        txtString.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStringActionPerformed(evt);
            }
        });
        txtString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStringKeyPressed(evt);
            }
        });
        jPanel1.add(txtString);
        txtString.setBounds(240, 150, 330, 40);

        txtResults.setBackground(new java.awt.Color(255, 255, 204));
        txtResults.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txtResults);
        txtResults.setBounds(240, 330, 330, 40);

        txtReverse.setBackground(new java.awt.Color(255, 255, 204));
        txtReverse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txtReverse);
        txtReverse.setBounds(240, 240, 330, 40);

        btnCheck.setBackground(new java.awt.Color(0, 204, 51));
        btnCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheck.setText("CHECK");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheck);
        btnCheck.setBounds(640, 150, 120, 40);

        btnClear.setBackground(new java.awt.Color(0, 204, 51));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(60, 420, 120, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setText("PALINDROME APPLICATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 850, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 340, 270, 190);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStringActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       
         this.txtString.setText("");
         this.txtResults.setText("");
         this.txtReverse.setText("");
         
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
    try {     
       String User_Input = this.txtString.getText();
       User_Input = User_Input.replaceAll("[\\W]", "");
       User_Input = User_Input.toLowerCase();
       String Stringreverse = "";
       
            Stack My_Stack = new Stack();
            
       int inputLength = User_Input.length();
       
         for(int i = 0; i<inputLength; i++){
                
            My_Stack.push(User_Input.charAt(i));           
                 
         }   
       while(!My_Stack.isEmpty()){
            
           Stringreverse = Stringreverse + My_Stack.pop();
            
       }
       if(!this.txtString.getText().equals("")){
                
           StringBuffer ab = new StringBuffer(User_Input).reverse();
           this.txtReverse.setText(""+ab);
                
           if(Stringreverse.equals(User_Input)){
                    
             this.txtResults.setText("Palindrome");
             this.txtResults.setVisible(true);
             JOptionPane.showMessageDialog(null,"User Input is a Palindrome","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                               
           }else if(!Stringreverse.equals(User_Input)){
                
             this.txtResults.setText("Not a Palindrome");
             this.txtResults.setVisible(true);
             JOptionPane.showMessageDialog(null,"User Input is Not a Palindrome","SUCCESS",JOptionPane.INFORMATION_MESSAGE);
                
           }
       }else{         
          throw new NullPointerException("Please Insert String Value");
                  
       }         
    } catch (NullPointerException e) {
            
        JOptionPane.showMessageDialog(rootPane, e);      
    }  
    }//GEN-LAST:event_btnCheckActionPerformed

    private void txtStringKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStringKeyPressed
        
    }//GEN-LAST:event_txtStringKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(palindromefram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(palindromefram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(palindromefram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(palindromefram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new palindromefram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtResults;
    private javax.swing.JTextField txtReverse;
    private javax.swing.JTextField txtString;
    // End of variables declaration//GEN-END:variables
}
